name: "[DANGEROUS] Warn if changed actions"

on:
  pull_request_target:
    paths:
      - .github/workflows/**

permissions:
  pull-requests: write

jobs:
  comment-for-pr:
    runs-on: ubuntu-latest
    env:
      PR_URL: ${{ github.event.pull_request.html_url }}
      GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    steps:
      - name: Comment for PR
        run: gh pr comment "$PR_URL" --body "⚠️ Actionsファイルの変更を検知しました。secretsを外部送信するような差分がないか注意！"
