name: "Detect actions diff"

on:
  pull_request:
    paths:
      - .github/workflows/**

permissions:
  pull-requests: write

jobs:
  detect-actions-diff:
    runs-on: ubuntu-latest
    env:
      PR_URL: ${{ github.event.pull_request.html_url }}
      GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    steps:
      - name: Warn if changed actions
        run: gh pr comment "$PR_URL" --body "⚠️ Actionsファイルの変更を検知しました。secretsを外部送信するような差分がないか注意！"
